version: '3.9'

networks:
  testwork:
    
services:
  postgres_user:
    hostname: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
    networks:
      - testwork
    
  test_api:
    build: ./
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
    depends_on:
      - postgres_user
    networks:
      - testwork