version: '3.9'

networks:
  testwork:
    
services:
  test_api:
    build: ./
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "UserInfoDb"
    depends_on:
      - postgres_user
    networks:
      - testwork
  
  postgres_user:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "UserInfoDb"
    networks:
      - testwork